### ISSUE TITLE
too bad fps on GTX 1050 Mobile

### ISSUE THREAD

**Issue by dusker33** [skeggsb/nouveau#2]
we have notebook Dell XPS 9560 with 2 graphic cards/
lspci | grep -E "VGA|3D"
00:02.0 VGA compatible controller: Intel Corporation Device 591b (rev 04)
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)

System: 4.15.0-21-generic #22-Ubuntu SMP Tue May 1 13:26:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

glmark2
====================================
    glmark2 2014.03+git20150611.fa71af2d
====================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
    GL_VERSION:    3.0 Mesa 18.2.0-devel
=======================================================
[build] use-vbo=false: FPS: **2905** FrameTime: 0.344 ms

DRI_PRIME=1 glmark2
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     nouveau
    GL_RENDERER:   NV137
    GL_VERSION:    3.1 Mesa 18.2.0-devel
=======================================================
[build] use-vbo=false: FPS: **878** FrameTime: 1.139 ms

FPS on intel much more better :(

**Comment by imirkin** [comment]
Is there a question in here?

**Comment by dusker33** [comment]
It's a problem. FPS must be much more.
I don't understand is GTX 1050 Mobile supported by this driver or not?

**Comment by imirkin** [comment]
Why must it? And what's your definition of "supported"? It loads, you even get triangles rendered... If there are outputs connected, they light up.

**Comment by dusker33** [comment]
Nvidia original driver makes near 20000 fps.
Intel simple card makes 3000 fps.
Nouveau makes 800 fps.
It's impossible to make 3D work with this situation.
May be I need to setup driver, but I don't know how.
I don't want to use Nvidia original driver for other bad issue.
I hope I can use nouveau, but how? May be it's a little bit offtopic.

**Comment by imirkin** [comment]
NVIDIA won't release signed firmware. So no clock changes, and it boots to lowest clocks.

If you want good open-source support, use AMD or Intel.

**Comment by dusker33** [comment]
It's notebook. I must use what I have :(
May I change clocks by some settings to try to make it work better?

**Comment by dusker33** [comment]
may be it's a normal work
