### ISSUE TITLE
Can't reboot.

### ISSUE THREAD

**Issue by dusker33** [skeggsb/nouveau#3]
we have notebook Dell XPS 9560 with 2 graphic cards.
00:02.0 VGA compatible controller: Intel Corporation Device 591b (rev 04)
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)

System: 4.15.0-21-generic #22-Ubuntu SMP Tue May 1 13:26:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

When make suspend. It works for the first time. But after resume nether reboot and suspend does not work.

Log:
May 21 22:20:06 dell kernel: [  151.730049] Suspending console(s) (use no_console_suspend to debug)
May 21 22:20:06 dell kernel: [  166.947628] nouveau 0000:01:00.0: DRM: failed to idle channel 0 [DRM]
May 21 22:20:06 dell kernel: [  166.947666] pci_pm_suspend(): nouveau_pmops_suspend+0x0/0x80 [nouveau] returns -16
May 21 22:20:06 dell kernel: [  166.947668] dpm_run_callback(): pci_pm_suspend+0x0/0x150 returns -16
May 21 22:20:06 dell kernel: [  166.947670] PM: Device 0000:01:00.0 failed to suspend async: error -16
May 21 22:20:06 dell kernel: [  167.123902] PM: Some devices failed to suspend, or early wake event detected

if suspending - it fall to login screen.

if reboot - very long pause (1-2 min) then reboot. Sometimes show an error like: 
failed to idle channel 3
failed to idle channel 2
Sometimes does not show.

What else information I need to provide?

**Comment by imirkin** [comment]
This is not the proper forum for any of those. https://nouveau.freedesktop.org/wiki/ has information on troubleshooting, bugs, etc.

**Comment by dusker33** [comment]
it's a pity that noone has interest about bugs
